apiVersion: v1
appVersion: 0.16.0
description: Stolon - PostgreSQL cloud native High Availability.
home: https://github.com/sorintlab/stolon
icon: https://i.imgur.com/tIW8sAW.png
maintainers:
- email: gabriel.maeztu@iomed.health
  name: Gabi Maeztu
  url: https://iomed.health
- email: juanmanuel.vizcaino@iomed.health
  name: Juan Manuel Vizcaino
  url: https://iomed.health
name: stolon
sources:
- https://github.com/sorintlab/stolon
- https://github.com/iomedhealth/helm_stolon
version: 1.7.2
