name: Release Drafter

on:
  push:
    branches:
      - master
      - main

jobs:
  update_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
